/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dostojic.theatreclient.view.play;

import javax.swing.ImageIcon;
import javax.swing.JComponent;

/**
 *
 * @author dejan
 */
public class PPlay extends javax.swing.JPanel {
    
    PInsertPlay pInsertPlay;
    PListPlays pListPlays;
    
    /**
     * Creates new form PPlay
     */
    public PPlay() {
        initComponents();
        addPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
    
    private void addPanels(){
        ImageIcon icon = null;
        
        pListPlays = new PListPlays();
        pInsertPlay = new PInsertPlay(pListPlays.getTablePlays());
        tabbedPane.addTab("Nova predstava", icon, pInsertPlay, "Ubaci novu predstavu");
        tabbedPane.addTab("Lista predstava", icon, pListPlays, "Prikaži postojeće predstave");
    }
    
}
