/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dostojic.theatreclient.view.artist;

import com.dostojic.common.model.User;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author dejan
 */
public class FArtist extends javax.swing.JDialog {

    User user;
    PInsertArtist insertPanel;
    PListArtists listPanel;
    
    /**
     * Creates new form FArtist
     */
    private FArtist() {
        super();
        initComponents();
        addPanes();
        this.setLayout(new GridLayout(1, 1));
        this.pack();
    }
    
    private static FArtist instance;
    
    public static FArtist getInstance(){
        if (instance == null){
            instance = new FArtist();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    private void addPanes() {
        ImageIcon icon = null;
        
        insertPanel = new PInsertArtist();
        tabbedPane.addTab("Ubaci umetnika", icon, insertPanel,
                "Ubacuje novog umetnika");
        tabbedPane.setMnemonicAt(0, KeyEvent.VK_1);
        
        listPanel = new PListArtists();
        tabbedPane.addTab("Izlistaj umetnike", icon, listPanel,
                "Izlistaj postojeće umetnike");
        tabbedPane.setMnemonicAt(1, KeyEvent.VK_2);
        
    }

    private JComponent makeTextPanel(String text) {
        JPanel panel = new JPanel(false);
        JLabel filler = new JLabel(text);
        filler.setHorizontalAlignment(JLabel.CENTER);
        panel.setLayout(new GridLayout());
        panel.add(filler);
        return panel;
    }
    
    public void refresh(){
        listPanel.fillTable();
    }

    public void setUser(User user) {
        this.user = user;
    }
    
}
